version: '3.4'

services:
  tinycrm.api:
    image: ${DOCKER_REGISTRY-}tinycrmapi
    build:
      context: .
      dockerfile: TinyCRM.API/Dockerfile
    environment:
      - ConnectionStrings__Default=Server=tinycrm.db;Database=TinyCrm;UID=sa;Password=Leron@1605;TrustServerCertificate=True;
      - ConnectionStrings__Redis=tiycrm.redis
    depends_on:
      - tinycrm.db
      - tiycrm.redis
    ports:
      - "5000:80"
  tinycrm.db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    user: root
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=Leron@1605
    volumes:
      - tinycrm:/var/opt/mssql/data
  tiycrm.redis:
    image: redis
    ports:
      - "6379:6379"
volumes:
  tinycrm:
    external: true